channels:
- conda-forge
dependencies:
- pyiron_atomistics
- pyiron_gpl
- pyiron_continuum
- lammps=2021.02.10
- sqsgenerator
- damask
- vtk
- itkwidgets
- pyvista
- h5py
- nglview
- seaborn
- papermill
