#!/bin/bash

# ngl view for jupyter
jupyter nbextension install nglview --py --sys-prefix
jupyter nbextension enable nglview --py --sys-prefix

# ngl view for jupyter lab
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install nglview-js-widgets

# pyiron setup
printf "[DEFAULT]\nTOP_LEVEL_DIRS = ${HOME}\nRESOURCE_PATHS = /srv/conda/envs/notebook/share/pyiron" > ${HOME}/.pyiron

# clone latest development version of DAMASK 
git clone https://github.com/eisenforschung/DAMASK.git
cd DAMASK 
# git checkout -b development
git checkout 264fab44
patch -p1 < ../binder/python.patch

# update python wrapper to latest development version 
cd python
cp ../VERSION .
pip install . 
cd ..

# update processing to the latest development version 
for f in $(ls processing/pre/*); do
     n=$(basename $f)
     cp -r $f ${NB_PYTHON_PREFIX}/bin/${n%.*};
 done
 for f in $(ls processing/post/*); do
     n=$(basename $f)
     cp -r $f ${NB_PYTHON_PREFIX}/bin/${n%.*};
 done
